Deprecate rsync support
pytest-dev/pytest-xdist pull request #828
Opened 2022-10-24 11:58 UTC by nicoddemus

Fix #825

2022-10-24 13:12 UTC, RonnyPfannschmidt requested changes
https://github.com/pytest-dev/pytest-xdist/blob/master/src/xdist/newhooks.py#L28

the hooks about rsync stop/start also need a update

2022-10-24 13:24 UTC, nicoddemus commented
Good catch, done, thanks!

2022-10-24 14:33 UTC, RonnyPfannschmidt approved these changes

2022-10-24 16:02 UTC, merged

2022-10-26 16:11 UTC, henryiii commented
In pypa/build#527, I'm getting:

```
py39 run-test: commands[0] | pytest -ra --cov --cov-config pyproject.toml --cov-report=html:/home/runner/work/build/build/.tox/py39/htmlcov --cov-context=test --cov-report=xml:/home/runner/work/build/build/.tox/coverage.py39.xml -n auto
INTERNALERROR> Traceback (most recent call last):
INTERNALERROR>   File "/home/runner/work/build/build/.tox/py39/lib/python3.9/site-packages/_pytest/main.py", line 266, in wrap_session
INTERNALERROR>     config._do_configure()
INTERNALERROR>   File "/home/runner/work/build/build/.tox/py39/lib/python3.9/site-packages/_pytest/config/__init__.py", line 1037, in _do_configure
INTERNALERROR>     self.hook.pytest_configure.call_historic(kwargs=dict(config=self))
INTERNALERROR>   File "/home/runner/work/build/build/.tox/py39/lib/python3.9/site-packages/pluggy/_hooks.py", line 277, in call_historic
INTERNALERROR>     res = self._hookexec(self.name, self.get_hookimpls(), kwargs, False)
INTERNALERROR>   File "/home/runner/work/build/build/.tox/py39/lib/python3.9/site-packages/pluggy/_manager.py", line 80, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
INTERNALERROR>   File "/home/runner/work/build/build/.tox/py39/lib/python3.9/site-packages/pluggy/_callers.py", line 60, in _multicall
INTERNALERROR>     return outcome.get_result()
INTERNALERROR>   File "/home/runner/work/build/build/.tox/py39/lib/python3.9/site-packages/pluggy/_result.py", line 60, in get_result
INTERNALERROR>     raise ex[1].with_traceback(ex[2])
INTERNALERROR>   File "/home/runner/work/build/build/.tox/py39/lib/python3.9/site-packages/pluggy/_callers.py", line 39, in _multicall
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "/home/runner/work/build/build/.tox/py39/lib/python3.9/site-packages/xdist/plugin.py", line 214, in pytest_configure
INTERNALERROR>     config.issue_config_time_warning(warning, 2)
INTERNALERROR>   File "/home/runner/work/build/build/.tox/py39/lib/python3.9/site-packages/_pytest/config/__init__.py", line 1394, in issue_config_time_warning
INTERNALERROR>     warnings.warn(warning, stacklevel=stacklevel)
INTERNALERROR> DeprecationWarning: The --rsyncdir command line argument and rsyncdirs config variable are deprecated.
INTERNALERROR> The rsync feature will be removed in pytest-xdist 4.0.
ERROR: InvocationError for command /home/runner/work/build/build/.tox/py39/bin/pytest -ra --cov --cov-config pyproject.toml --cov-report=html:/home/runner/work/build/build/.tox/py39/htmlcov --cov-context=test --cov-report=xml:/home/runner/work/build/build/.tox/coverage.py39.xml -n auto (exited with code 3)
```

Build doesn't touch `rsyncdir`, so is this leaking in from coverage or some other plugin? The traceback just goes to pluggy which IIRC is pytest's tool for running plugins.